#!/bin/bash
echo "om een release te maken moet je uitvoeren:"
echo "edit configure.in en verhoog / stel het versie nummer in"
echo "voer uit: dch -v *NIEUW VERSIE NUMMER* en type leuk stukje tekst"
echo "voer uit fakeroot debian/rules binary"
echo "voor uit scp ../mjs_4.0rc4_i386.deb root@serv:/srv/www/html/mjs/."
echo "Log in op de server en voer uit:"
echo "cd /srv/www/html/mjs"
echo "dpkg-scanpackages -m . > Packages"
echo "gzip -c Packages  > Packages.gz"
echo "chroot /srv/tftpboot/images/"
echo "apt-get update"
echo "apt-get install mjs"
echo "DRAAI GEEEEEEEEEEEEEEN apt-get dist-upgrade / apt-get upgrade in de chroot env!!!"
