Document: mjs
Title: Debian mjs Manual
Author: <insert document author here>
Abstract: This manual describes what mjs is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mjs/mjs.sgml.gz

Format: postscript
Files: /usr/share/doc/mjs/mjs.ps.gz

Format: text
Files: /usr/share/doc/mjs/mjs.text.gz

Format: HTML
Index: /usr/share/doc/mjs/html/index.html
Files: /usr/share/doc/mjs/html/*.html

  
